// The built-in exercise library: the common gym lifts, named plainly as
// "Equipment + movement" (e.g. "Machine Incline Press"). Each one points at
// a drawn animation pattern in figures.js (`fig`) and gets short how-to
// steps for that movement.

// [id, name, category, equipment, figure pattern]
const RAW = [
  // ---------- Chest ----------
  ["barbell-bench-press", "Barbell Bench Press", "Chest", "barbell", "benchPress"],
  ["dumbbell-bench-press", "Dumbbell Bench Press", "Chest", "dumbbell", "benchPress"],
  ["machine-chest-press", "Machine Chest Press", "Chest", "machine", "chestPress"],
  ["smith-bench-press", "Smith Machine Bench Press", "Chest", "machine", "benchPress"],
  ["barbell-incline-press", "Barbell Incline Press", "Chest", "barbell", "inclinePress"],
  ["dumbbell-incline-press", "Dumbbell Incline Press", "Chest", "dumbbell", "inclinePress"],
  ["machine-incline-press", "Machine Incline Press", "Chest", "machine", "inclinePress"],
  ["barbell-decline-press", "Barbell Decline Press", "Chest", "barbell", "declinePress"],
  ["dumbbell-fly", "Dumbbell Fly", "Chest", "dumbbell", "flyFront"],
  ["cable-fly", "Cable Fly", "Chest", "cable", "flyFront"],
  ["machine-fly", "Machine Fly (Pec Deck)", "Chest", "machine", "flyFront"],
  ["push-up", "Push-Up", "Chest", "body only", "pushUp"],
  ["chest-dip", "Chest Dip", "Chest", "body only", "dip"],
  ["dumbbell-decline-press", "Dumbbell Decline Press", "Chest", "dumbbell", "declinePress"],
  ["cable-chest-press", "Cable Chest Press", "Chest", "cable", "chestPress"],

  // ---------- Back ----------
  ["pull-up", "Pull-Up", "Back", "body only", "pullUp"],
  ["chin-up", "Chin-Up", "Back", "body only", "pullUp"],
  ["machine-assisted-pull-up", "Machine Assisted Pull-Up", "Back", "machine", "pullUp"],
  ["cable-lat-pulldown", "Cable Lat Pulldown", "Back", "cable", "pulldown"],
  ["cable-close-grip-pulldown", "Cable Close-Grip Pulldown", "Back", "cable", "pulldown"],
  ["machine-lat-pulldown", "Machine Lat Pulldown", "Back", "machine", "pulldown"],
  ["barbell-row", "Barbell Row", "Back", "barbell", "bentRow"],
  ["dumbbell-row", "Dumbbell Row", "Back", "dumbbell", "bentRow"],
  ["cable-seated-row", "Cable Seated Row", "Back", "cable", "seatedRow"],
  ["machine-row", "Machine Row", "Back", "machine", "seatedRow"],
  ["machine-t-bar-row", "Machine T-Bar Row", "Back", "machine", "bentRow"],
  ["cable-straight-arm-pulldown", "Cable Straight-Arm Pulldown", "Back", "cable", "straightPulldown"],
  ["barbell-deadlift", "Barbell Deadlift", "Back", "barbell", "deadlift"],
  ["barbell-shrug", "Barbell Shrug", "Back", "barbell", "shrug"],
  ["dumbbell-shrug", "Dumbbell Shrug", "Back", "dumbbell", "shrug"],
  ["back-extension", "Back Extension", "Back", "body only", "backExt"],

  // ---------- Shoulders ----------
  ["barbell-overhead-press", "Barbell Overhead Press", "Shoulders", "barbell", "ohp"],
  ["dumbbell-shoulder-press", "Dumbbell Shoulder Press", "Shoulders", "dumbbell", "seatedOhp"],
  ["machine-shoulder-press", "Machine Shoulder Press", "Shoulders", "machine", "seatedOhp"],
  ["dumbbell-arnold-press", "Dumbbell Arnold Press", "Shoulders", "dumbbell", "seatedOhp"],
  ["dumbbell-lateral-raise", "Dumbbell Lateral Raise", "Shoulders", "dumbbell", "lateral"],
  ["cable-lateral-raise", "Cable Lateral Raise", "Shoulders", "cable", "lateral"],
  ["machine-lateral-raise", "Machine Lateral Raise", "Shoulders", "machine", "lateral"],
  ["dumbbell-front-raise", "Dumbbell Front Raise", "Shoulders", "dumbbell", "frontRaise"],
  ["cable-front-raise", "Cable Front Raise", "Shoulders", "cable", "frontRaise"],
  ["dumbbell-rear-delt-fly", "Dumbbell Rear Delt Fly", "Shoulders", "dumbbell", "rearFly"],
  ["machine-rear-delt-fly", "Machine Rear Delt Fly", "Shoulders", "machine", "rearFly"],
  ["cable-face-pull", "Cable Face Pull", "Shoulders", "cable", "facePull"],
  ["barbell-upright-row", "Barbell Upright Row", "Shoulders", "barbell", "uprightRow"],
  ["cable-upright-row", "Cable Upright Row", "Shoulders", "cable", "uprightRow"],
  ["smith-shoulder-press", "Smith Machine Shoulder Press", "Shoulders", "machine", "seatedOhp"],

  // ---------- Legs ----------
  ["barbell-squat", "Barbell Squat", "Legs", "barbell", "squat"],
  ["barbell-front-squat", "Barbell Front Squat", "Legs", "barbell", "frontSquat"],
  ["dumbbell-goblet-squat", "Dumbbell Goblet Squat", "Legs", "dumbbell", "gobletSquat"],
  ["smith-squat", "Smith Machine Squat", "Legs", "machine", "squat"],
  ["machine-hack-squat", "Machine Hack Squat", "Legs", "machine", "hackSquat"],
  ["machine-leg-press", "Machine Leg Press", "Legs", "machine", "legPress"],
  ["barbell-romanian-deadlift", "Barbell Romanian Deadlift", "Legs", "barbell", "rdl"],
  ["dumbbell-romanian-deadlift", "Dumbbell Romanian Deadlift", "Legs", "dumbbell", "rdl"],
  ["dumbbell-lunge", "Dumbbell Lunge", "Legs", "dumbbell", "lunge"],
  ["barbell-lunge", "Barbell Lunge", "Legs", "barbell", "lunge"],
  ["dumbbell-bulgarian-split-squat", "Dumbbell Bulgarian Split Squat", "Legs", "dumbbell", "splitSquat"],
  ["dumbbell-step-up", "Dumbbell Step-Up", "Legs", "dumbbell", "stepUp"],
  ["machine-leg-extension", "Machine Leg Extension", "Legs", "machine", "legExt"],
  ["machine-lying-leg-curl", "Machine Lying Leg Curl", "Legs", "machine", "lyingCurl"],
  ["machine-seated-leg-curl", "Machine Seated Leg Curl", "Legs", "machine", "seatedCurl"],
  ["machine-standing-calf-raise", "Machine Standing Calf Raise", "Legs", "machine", "calfRaise"],
  ["machine-seated-calf-raise", "Machine Seated Calf Raise", "Legs", "machine", "seatedCalf"],
  ["barbell-hip-thrust", "Barbell Hip Thrust", "Legs", "barbell", "hipThrust"],
  ["machine-hip-abduction", "Machine Hip Abduction", "Legs", "machine", "abduction"],
  ["machine-hip-adduction", "Machine Hip Adduction", "Legs", "machine", "adduction"],
  ["cable-glute-kickback", "Cable Glute Kickback", "Legs", "cable", "kickback"],
  ["kettlebell-swing", "Kettlebell Swing", "Legs", "kettlebell", "rdl"],
  ["bodyweight-squat", "Bodyweight Squat", "Legs", "body only", "squat"],
  ["walking-lunge", "Walking Lunge", "Legs", "body only", "lunge"],
  ["barbell-sumo-deadlift", "Barbell Sumo Deadlift", "Legs", "barbell", "deadlift"],
  ["barbell-good-morning", "Barbell Good Morning", "Legs", "barbell", "rdl"],

  // ---------- Arms ----------
  ["barbell-curl", "Barbell Curl", "Arms", "barbell", "curl"],
  ["ez-bar-curl", "EZ-Bar Curl", "Arms", "barbell", "curl"],
  ["dumbbell-curl", "Dumbbell Curl", "Arms", "dumbbell", "curl"],
  ["dumbbell-hammer-curl", "Dumbbell Hammer Curl", "Arms", "dumbbell", "curl"],
  ["dumbbell-incline-curl", "Dumbbell Incline Curl", "Arms", "dumbbell", "curl"],
  ["dumbbell-concentration-curl", "Dumbbell Concentration Curl", "Arms", "dumbbell", "preacherCurl"],
  ["cable-curl", "Cable Curl", "Arms", "cable", "curl"],
  ["machine-preacher-curl", "Machine Preacher Curl", "Arms", "machine", "preacherCurl"],
  ["cable-triceps-pushdown", "Cable Triceps Pushdown", "Arms", "cable", "pushdown"],
  ["cable-rope-pushdown", "Cable Rope Pushdown", "Arms", "cable", "pushdown"],
  ["cable-overhead-triceps-extension", "Cable Overhead Triceps Extension", "Arms", "cable", "overheadExtCable"],
  ["dumbbell-overhead-triceps-extension", "Dumbbell Overhead Triceps Extension", "Arms", "dumbbell", "overheadExt"],
  ["barbell-skull-crusher", "Barbell Skull Crusher", "Arms", "barbell", "skullCrusher"],
  ["barbell-close-grip-bench-press", "Barbell Close-Grip Bench Press", "Arms", "barbell", "benchPress"],
  ["machine-triceps-extension", "Machine Triceps Extension", "Arms", "machine", "pushdown"],
  ["triceps-dip", "Triceps Dip", "Arms", "body only", "dip"],
  ["dumbbell-skull-crusher", "Dumbbell Skull Crusher", "Arms", "dumbbell", "skullCrusher"],
  ["cable-hammer-curl", "Cable Hammer Curl", "Arms", "cable", "curl"],
  ["barbell-reverse-curl", "Barbell Reverse Curl", "Arms", "barbell", "curl"],

  // ---------- Core ----------
  ["crunch", "Crunch", "Core", "body only", "crunch"],
  ["cable-crunch", "Cable Crunch", "Core", "cable", "cableCrunch"],
  ["machine-crunch", "Machine Crunch", "Core", "machine", "machineCrunch"],
  ["hanging-leg-raise", "Hanging Leg Raise", "Core", "body only", "hangingLegRaise"],
  ["lying-leg-raise", "Lying Leg Raise", "Core", "body only", "lyingLegRaise"],
  ["plank", "Plank", "Core", "body only", "plank"],
  ["side-plank", "Side Plank", "Core", "body only", "sidePlank"],
  ["dumbbell-russian-twist", "Dumbbell Russian Twist", "Core", "dumbbell", "russianTwist"],
  ["ab-wheel-rollout", "Ab Wheel Rollout", "Core", "body only", "abWheel"],
  ["cable-woodchopper", "Cable Woodchopper", "Core", "cable", "woodchop"],
  ["bicycle-crunch", "Bicycle Crunch", "Core", "body only", "crunch"],
  ["decline-crunch", "Decline Crunch", "Core", "body only", "crunch"]
];

// Short how-to per movement pattern.
const HOW = {
  benchPress: ["Lie on the bench with your eyes under the bar/handles and feet flat on the floor.", "Lower the weight under control to your mid-chest, elbows about 45° from your body.", "Press back up until your arms are straight, keeping your shoulder blades pulled back."],
  chestPress: ["Sit with your back against the pad and the handles at chest height.", "Press the handles forward until your arms are almost straight.", "Let them come back slowly until you feel a stretch across your chest."],
  inclinePress: ["Set the bench to about 30–45° and sit back with your feet planted.", "Lower the weight to your upper chest with elbows slightly tucked.", "Press up and slightly back until your arms are straight."],
  declinePress: ["Lie on the decline bench with your legs secured.", "Lower the weight to your lower chest.", "Press back up to straight arms."],
  flyFront: ["Start with your arms wide and a soft bend in the elbows.", "Bring your hands together in front of your chest in a wide arc, squeezing your chest.", "Open back out slowly until you feel a stretch, keeping the elbow bend the same."],
  pushUp: ["Hands a little wider than your shoulders, body in a straight line from head to heels.", "Lower your chest towards the floor with elbows about 45° from your body.", "Push back up to straight arms without letting your hips sag."],
  dip: ["Support yourself on the bars with straight arms.", "Lower yourself by bending your elbows until your upper arms are about level with the floor.", "Push back up to straight arms."],
  pullUp: ["Hang from the bar with straight arms (palms away for pull-ups, towards you for chin-ups).", "Pull your chest up towards the bar, driving your elbows down.", "Lower yourself all the way down under control."],
  pulldown: ["Sit with your thighs under the pads and grab the bar a little wider than your shoulders.", "Pull the bar down to your upper chest, leaning back slightly and driving your elbows down.", "Let it rise slowly until your arms are straight."],
  bentRow: ["Hinge forward at the hips with a flat back and slightly bent knees.", "Pull the weight towards your lower ribs, squeezing your shoulder blades together.", "Lower it slowly until your arms are straight."],
  seatedRow: ["Sit tall with your chest up and a slight bend in your knees.", "Pull the handle to your stomach, squeezing your shoulder blades together.", "Let your arms extend forward slowly without rounding your back."],
  straightPulldown: ["Stand facing the cable with arms straight and a slight forward lean.", "Pull the bar down to your thighs in an arc, keeping your arms straight.", "Let it return slowly to about head height."],
  deadlift: ["Feet hip-width apart, bar over the middle of your feet.", "Grip the bar, flatten your back and push the floor away to stand up tall.", "Lower the bar by pushing your hips back, keeping it close to your legs."],
  shrug: ["Stand tall holding the weight with straight arms.", "Lift your shoulders straight up towards your ears.", "Pause, then lower them slowly."],
  backExt: ["Set the pad just below your hips and hook your feet under the rollers.", "Lower your upper body forward with a flat back.", "Raise it back up until your body is in a straight line."],
  ohp: ["Stand with the bar at your collarbone, hands just outside your shoulders.", "Press it straight overhead, moving your head back slightly to let it pass.", "Lower it back to your collarbone under control."],
  seatedOhp: ["Sit with your back supported and the weight at shoulder height.", "Press it overhead until your arms are almost straight.", "Lower it back to shoulder height slowly."],
  lateral: ["Stand tall with the weight at your sides and a slight bend in your elbows.", "Raise your arms out to the side until they're level with your shoulders.", "Lower them slowly without swinging."],
  frontRaise: ["Stand tall with the weight in front of your thighs.", "Raise it in front of you to shoulder height with nearly straight arms.", "Lower it slowly."],
  rearFly: ["Hinge forward (or sit facing the machine pad) with arms hanging down.", "Raise your arms out to the side, leading with your elbows.", "Lower slowly, keeping your back flat."],
  facePull: ["Set the cable at about head height with a rope attachment.", "Pull the rope towards your face, elbows high and wide, hands ending beside your ears.", "Return slowly until your arms are straight."],
  uprightRow: ["Hold the bar in front of your thighs, hands about shoulder-width.", "Pull it up close to your body until your elbows reach shoulder height.", "Lower it slowly."],
  squat: ["Bar resting on your upper back, feet about shoulder-width apart.", "Sit down and back until your thighs are about level with the floor, chest up.", "Drive through your whole foot to stand back up."],
  frontSquat: ["Rest the bar on the front of your shoulders with elbows high.", "Squat down, keeping your torso upright.", "Stand back up through your whole foot."],
  gobletSquat: ["Hold the dumbbell upright against your chest.", "Squat down between your knees, keeping your chest up.", "Stand back up through your whole foot."],
  hackSquat: ["Stand on the platform with your back and shoulders against the pads.", "Lower yourself until your thighs are about level with the platform.", "Push back up without locking your knees hard."],
  legPress: ["Sit with your back flat on the pad and feet shoulder-width on the platform.", "Lower the platform until your knees are bent to about 90°.", "Press it back up without fully locking your knees."],
  rdl: ["Stand holding the weight in front of your thighs with soft knees.", "Push your hips back and lower the weight along your legs until you feel a hamstring stretch.", "Drive your hips forward to stand back up tall."],
  lunge: ["Stand tall holding the weight.", "Step forward and lower until both knees are bent to about 90°.", "Push off the front foot back to standing and switch legs."],
  splitSquat: ["Stand in front of a bench with the top of your back foot resting on it.", "Lower straight down until your front thigh is about level with the floor.", "Push through your front foot to stand back up."],
  stepUp: ["Stand facing a box or bench holding the weights.", "Step up with one foot and drive through it until you're standing on the box.", "Step back down under control and repeat."],
  legExt: ["Sit with the pad on the front of your lower shins.", "Straighten your legs until they're almost locked.", "Lower slowly."],
  lyingCurl: ["Lie face down with the pad just above your heels.", "Curl your heels towards your glutes.", "Lower slowly to straight legs."],
  seatedCurl: ["Sit with the pad behind your lower calves and the thigh pad secured.", "Bend your knees to pull the pad down and back.", "Let it return slowly."],
  calfRaise: ["Stand with the balls of your feet on the edge of the platform.", "Rise up as high as you can onto your toes.", "Lower your heels below the platform for a stretch."],
  seatedCalf: ["Sit with the pad on your thighs and the balls of your feet on the platform.", "Push up onto your toes as high as you can.", "Lower your heels slowly for a stretch."],
  hipThrust: ["Upper back against a bench, bar across your hips, feet flat on the floor.", "Drive your hips up until your body is flat from shoulders to knees, squeezing your glutes.", "Lower your hips slowly."],
  abduction: ["Sit with the pads on the outside of your knees.", "Push your knees out as far as you can.", "Let them come back slowly."],
  adduction: ["Sit with the pads on the inside of your knees.", "Squeeze your knees together.", "Let them open back out slowly."],
  kickback: ["Attach the ankle strap and face the machine, holding on for balance.", "Kick your leg straight back, squeezing your glute.", "Return slowly without arching your back."],
  curl: ["Stand tall holding the weight with your arms straight.", "Curl it up towards your shoulders, keeping your elbows by your sides.", "Lower it slowly to straight arms."],
  preacherCurl: ["Rest the back of your upper arm on the pad (or your thigh).", "Curl the weight up towards your shoulder.", "Lower it slowly until your arm is almost straight."],
  pushdown: ["Stand facing the cable with your elbows tucked by your sides.", "Push the handle down until your arms are straight.", "Let it rise slowly to about chest height, keeping your elbows still."],
  overheadExt: ["Hold the weight overhead with both hands.", "Lower it behind your head by bending your elbows, keeping them pointing up.", "Straighten your arms back overhead."],
  overheadExtCable: ["Face away from the cable holding the rope behind your head.", "Straighten your arms forward and up.", "Bend your elbows to bring the rope back behind your head."],
  skullCrusher: ["Lie on the bench holding the bar above your chest with straight arms.", "Bend your elbows to lower the bar towards your forehead.", "Straighten your arms back up."],
  crunch: ["Lie on your back with your knees bent and feet flat.", "Curl your shoulders off the floor towards your knees.", "Lower back down slowly."],
  cableCrunch: ["Kneel facing the cable holding the rope beside your head.", "Crunch down, bringing your elbows towards your knees.", "Return slowly to upright."],
  machineCrunch: ["Sit with the pads on your chest or the handles in your hands.", "Curl your torso forward and down.", "Return slowly."],
  hangingLegRaise: ["Hang from the bar with straight arms.", "Raise your legs until they're level with your hips (or higher).", "Lower them slowly without swinging."],
  lyingLegRaise: ["Lie on your back with your legs straight.", "Raise your legs until they point at the ceiling.", "Lower them slowly without letting your lower back arch."],
  plank: ["Forearms on the floor under your shoulders, body straight from head to heels.", "Brace your stomach and squeeze your glutes.", "Hold — don't let your hips sag or pike up."],
  sidePlank: ["Lie on your side with your forearm under your shoulder.", "Lift your hips so your body is in a straight line.", "Hold, then switch sides."],
  russianTwist: ["Sit with your knees bent, leaning back slightly, holding the weight.", "Rotate your torso to bring the weight beside one hip.", "Rotate to the other side."],
  woodchop: ["Stand side-on to a high cable holding the handle with both hands.", "Pull it diagonally down across your body, rotating through your torso.", "Return slowly to the start."],
  abWheel: ["Kneel holding the wheel under your shoulders.", "Roll it forward as far as you can while keeping your back flat.", "Pull it back in using your stomach."],
  stand: ["Set up in a stable position.", "Move the weight through a full, controlled range.", "Return slowly to the start."]
};

export const LIBRARY = RAW.map(([id, name, cat, equipment, fig]) => ({
  id, name, cat, equipment, fig, isCustom: false,
  instructions: HOW[fig] || HOW.stand
}));
